### ISSUE TITLE
Error: Cannot find module 'ethereumjs-util'

### ISSUE THREAD

**Issue by europound** [brutebrothers/mist-password-recovery#3]
ternal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'ethereumjs-util'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/wallets/Downloads/mist-password-recovery-master/lib/decrypt.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by europound** [comment]
npm install ethereumjs-util
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ ethereumjs-util@7.0.7
updated 1 package and audited 76 packages in 3.043s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by stunjiturner** [comment]
have you figured out how to get the script working, I am having the same error of MAC /

**Comment by pieterhouwen** [comment]
You need to run ```npm i``` before using the program
